### PR TITLE
PIPE2D-922: Add more filters to pfs/fluxCal/bandpass.

### PR DESCRIPTION
**Pull request by SogoMineo**
Added many filters including those of HSC, PS1, Gaia and SDSS.
This commit overwrites the previous transmission curve of "i" filter.
In the new transmission curve, unlike in the previous one,
all of the atmosphere, telescope, camera, filter, and detector
are taken account of.

### CODE REVIEW

**Comment by SogoMineo** [comment]
These changes are required by drp_stella/tickets/PIPE2D-922. This commit changes the meaning of "i" to be HSC-I (not I2). The name of HSC-I2 will be "i2". I don't insist the superiority of the new nomenclature. I am willing to reconsider the change if you don't like it.

**Review by PaulPrice — COMMENTED** [review]
We need a README citing the source for each of these, and defining the format and units.
The wavelengths appear to be in angstroms, whereas PFS typically uses nm everywhere else so I suggest we change these to match.

**Comment by SogoMineo** [comment]
I changed the unit of the wavelengths to nm, and revised `pfs/fluxCal/bandpass/README.txt`.

**Comment by SogoMineo** [comment]
I realized that the unit of wavelength must be nm not in the atmosphere but in the vacuum. Maybe I should revise the response function files further.

**Comment by SogoMineo** [comment]
Converting wavelength in air to wavelength in vacuum is more complicated than I thought. The difference between them will not be significant in photometering broad-band fluxes. So let me merge this PR now and think about the conversion later.

**Pull request merged**
